### ISSUE TITLE
Test harness for advanced Composed Task scenarios

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-acceptance-tests#324]
The goal is to [increase the coverage](https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests/blob/master/src/test/java/org/springframework/cloud/dataflow/acceptance/test/ComposedTaskTests.java) from 3 -> 50!

- [x] testFailedGraph `failedStep && AAA` 
- [x] testEmbeddedFailedGraph `AAA && failedStep && BBB`
- [x] testSequential `AAA && BBB && CCC`
- [x] splitTest `<AAA||BBB||CCC>`
- [x] nestedSplit `<<AAA || BBB > && CCC || DDD>`
- [x] twoSplitTest `<AAA||BBB||CCC> && <DDD||EEE>`
- [x] testSequentialAndSplit `AAA && <BBB||CCC||DDD> && EEE`
- [x] testSequentialTransitionAndSplit `AAA && FFF 'FAILED' -> EEE && <BBB||CCC> && DDD`
- [x] testSequentialTransitionAndSplitFailedInvalid `AAA && failedStep 'FAILED' -> EEE && FFF && <BBB||CCC> && DDD` should fail
- [x] testSequentialAndFailedSplit `AAA && <BBB||failedStep||DDD> && EEE`
- [x] testSequentialAndSplitWithFlow `AAA && <BBB && FFF||CCC||DDD> && EEE`
- [x] testFailedBasicTransition `failedStep 'FAILED' -> AAA * -> BBB` 
- [x] testSuccessBasicTransition `AAA 'FAILED' -> BBB * -> CCC`
- [x] testSuccessBasicTransitionWithTransition `AAA 'FAILED' -> BBB && CCC 'FAILED' -> DDD '*' -> EEE`
- [x] testSequenceFollowedBySuccessBasicTransitionSequence `DDD && AAA 'FAILED' -> BBB * -> CCC && EEE` should fail
- [x] testWildCardOnlyInLastPosition `AAA 'FAILED' -> BBB && CCC * -> DDD`
- [x] testFailedGraphRetry:  `failedStep && AAA` run execution, retry execution in which it will upon 2nd try failedStep succeeds.   
- [x] testEmbeddedFailedGraph `AAA && failedStep && BBB` run execution, retry execution in which it will upon 2nd try failedStep succeeds.   
- [x] testSequentialAndFailedSplitRetry `AAA && <BBB||failedStep||DDD> && EEE` run execution, retry execution in which it will upon 2nd try failedStep succeeds.   
- [x] testSequentialRetry `AAA && BBB && CCC` run execution, retry execution in which it will upon 2nd try it will fails.
- [ ] pass CTR properties with invalid values.  unaccessible urls for hosts, negative numbers for threads etc.

**Comment by cppwfs** [comment]
Linking this issue to https://github.com/spring-cloud/spring-cloud-dataflow-samples/issues/140.    This issue's result will provide a task batch application that will allow users to test Composed Tasks, task, and batch failures.
