### ISSUE TITLE
Reuse the ITs tests as ATs

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-dataflow-acceptance-tests#332]
Reuse the [SCDF ATs](https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests) platform provisioning scripts but replace the outdated ATs test code by reusing the `SDCF ITs` tests. 

The existing [SCDF ATs](https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests/tree/master/src/test/java/org/springframework/cloud/dataflow/acceptance/test) test code is outdated, not based on the SCDF Stream/Task DSLs. Most importantly the `ATs` represents only subset of test coverage compared to the [SDCF ITs](https://github.com/spring-cloud/spring-cloud-dataflow/tree/master/spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test).  Also at the moment we need to maintain tests with overlapping coverage in two separate codebases (e.g. ITs and ATs) and using different coding models and utilities.

Given that the [SDCF ITs](https://github.com/spring-cloud/spring-cloud-dataflow/tree/master/spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test) tests use the SCDF rest  clients (same as the ATs) they can be run against any platform provisioned by the ATs scripts.

For some tests, such as the Schedulers tests, that can only be run agains CF or K8s platforms only, evaluate the right codebase to maintain then. Still those tests should be written with the help of the Stream/Task DSL and the same test utilities used for the ITs. 

#### Tasks on the Data Flow ITs side
* [x] Generate ITs separate jar
* [x] harden the test utilities so they can run agains the supported platforms (CF, K8s, Local)
* [x] Align the IT test sets to ensure that they cover everything provided by the existing ATs test code. 
Dependes on https://github.com/spring-cloud/spring-cloud-dataflow/issues/4400

#### Tasks on the Data Flow ATs side
* [x] Remove the outdated ATs test code and use the tests from the ITs test jar instead.
* [x] Evaluate the best place to keep tests that runs only on CF or K8s platforms (such as Scheduler)
* [x] Improve the platform provisioning scripting to allow bulk apps registration during the creation phase
* [ ] deprecate/remove the local platform ATs as they are supersede by the ITs local tests.

**Comment by sabbyanandan** [comment]
This is now complete.
